### ISSUE TITLE
SER-FIQ Score Values 

### ISSUE THREAD

**Issue by gebaltso** [jankolf/ser-fiq-pytorch#4]
Hello! Is it possible to provide something like thresholds for the quality SER-FIQ Score? Eg does the 0.75 is a high score?
Cause even I test the method on total blurry face images the lowest value I get is around 0.64.

**Comment by jankolf** [comment]
Hi,
no, there is no threshold. You have to adapt the score based on your needs, e.g. to certain error rates etc.
